# KubeInvaders chart values
replicaCount: 1

image:
  repository: luckysideburn/kubeinvaders
  tag: "v1.9.7"
  pullPolicy: IfNotPresent

# Environment variables for namespace targeting
config:
  insecure_endpoint: "true"
  target_namespace: app1,app2

# Service
service:
  type: ClusterIP
  port: 8080
containerPort: 8080

# Prometheus scrape hints (for Splunk OTel)
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: /metrics

# Ingress
ingress:
  className: nginx
  enabled: true
  hostName: kubeinvaders.4.197.187.1.nip.io
  tls_enabled: false

# RBAC (to list namespaces and manage chaos jobs)
rbac:
  create: true
  clusterRole: true
